# Generated by Django 5.1.15 on 2026-03-28 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_college_data(apps, schema_editor):
    College = apps.get_model('students', 'College')
    Department = apps.get_model('students', 'Department')
    Announcement = apps.get_model('students', 'Announcement')
    Exam = apps.get_model('students', 'Exam')
    UserRole = apps.get_model('students', 'UserRole')

    college, _ = College.objects.get_or_create(
        code='SVCE',
        defaults={
            'name': 'Sri Venkateswara College of Engineering',
            'city': 'Tirupati',
            'state': 'Andhra Pradesh',
        },
    )

    Department.objects.filter(college__isnull=True).update(college=college)
    Announcement.objects.filter(college__isnull=True).update(college=college)
    Exam.objects.filter(college__isnull=True).update(college=college)
    UserRole.objects.filter(college__isnull=True).update(college=college)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_activitylog_id_alter_address_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'College Admin'), (2, 'HOD'), (3, 'Faculty'), (4, 'Student'), (5, 'Lab Staff'), (6, 'Principal')], default=4),
        ),
        migrations.AddField(
            model_name='announcement',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='students.college'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='students.college'),
        ),
        migrations.AddField(
            model_name='exam',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.college'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='students.college'),
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='students.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_college_data, migrations.RunPython.noop),
    ]
