# Generated by Django 5.1.15 on 2026-03-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_assignment_is_published_classroom_college_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='inter_college_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='inter_passed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='inter_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='registration_ids/'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='school_passed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='school_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.helpdeskticket')),
            ],
        ),
    ]
