# Generated by Django 5.1.15 on 2026-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_registrationrequest_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
