# Generated by Django 5.1.15 on 2026-03-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_registrationrequest_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='faculty_id_rule',
            field=models.CharField(default='FAC-{CODE}-{SERIAL}', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='student_id_rule',
            field=models.CharField(default='{YEAR}-{CODE}-{DEPT}-{SERIAL}', max_length=100),
        ),
    ]
