# Generated by Django 5.1.15 on 2026-03-31 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_leaveapplication_lessonplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('primary_color', models.CharField(default='#0d7377', help_text='Hex color e.g. #0d7377', max_length=7)),
                ('accent_color', models.CharField(default='#e6a817', help_text='Hex color e.g. #e6a817', max_length=7)),
                ('sidebar_dark', models.BooleanField(default=True, help_text='Dark sidebar (default) or light')),
                ('show_college_name_in_sidebar', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='students.college')),
            ],
        ),
    ]
