# Generated by Django 5.1.15 on 2026-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_college_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegebranding',
            name='sidebar_deep',
            field=models.CharField(default='#071e26', help_text='Sidebar background hex color', max_length=7),
        ),
    ]
