# Generated by Django 5.1.15 on 2026-03-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_add_sidebar_deep_to_college_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='hod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='students.department'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.IntegerField(choices=[(1, 'College Admin'), (2, 'HOD'), (3, 'Faculty'), (4, 'Student'), (5, 'Lab Staff'), (6, 'Principal')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('subject', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('college', 'code'), ('college', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('user', 'parent_type')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddConstraint(
            model_name='hod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department',), name='unique_active_hod_per_department'),
        ),
    ]
