# Generated by Django 5.1.15 on 2026-04-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_merge_models1_safe_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fee',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
