# Generated by Django 5.1.15 on 2026-04-01 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_fee_semester_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_type',
            field=models.CharField(choices=[('BE', 'B.E'), ('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('BSC', 'B.Sc'), ('MSC', 'M.Sc'), ('DIPLOMA', 'Diploma'), ('OTHER', 'Other')], default='BE', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='Syllabus year e.g. 2021-22. Leave blank for current.', max_length=9),
        ),
        migrations.AddField(
            model_name='subject',
            name='degree_type',
            field=models.CharField(choices=[('BE', 'B.E'), ('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('BSC', 'B.Sc'), ('MSC', 'M.Sc'), ('DIPLOMA', 'Diploma'), ('OTHER', 'Other')], default='BE', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab / Practical'), ('ELECTIVE', 'Elective'), ('PROJECT', 'Project / Seminar')], default='THEORY', max_length=10),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='assignment_marks',
            field=models.FloatField(blank=True, help_text='Assignment component (out of 20)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='attendance_marks',
            field=models.FloatField(blank=True, help_text='Attendance component (out of 5)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='ia1',
            field=models.FloatField(blank=True, help_text='Internal Assessment 1 (out of 30)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='ia2',
            field=models.FloatField(blank=True, help_text='Internal Assessment 2 (out of 30)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'degree_type', 'semester', 'code', 'academic_year')},
        ),
    ]
