# Generated by Django 5.1.15 on 2026-04-01 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_degree_type_subject_type_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree_type',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.IntegerField(choices=[(1, 'College Admin'), (2, 'HOD'), (3, 'Faculty'), (4, 'Student'), (5, 'Lab Staff'), (6, 'Principal'), (7, 'Exam Controller')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'College Admin'), (2, 'HOD'), (3, 'Faculty'), (4, 'Student'), (5, 'Lab Staff'), (6, 'Principal'), (7, 'Exam Controller')], default=4),
        ),
        migrations.CreateModel(
            name='ExamController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('designation', models.CharField(default='Exam Controller', max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_controllers', to='students.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CIE', 'Continuous Internal Evaluation'), ('SEE', 'Semester End Examination'), ('PRACTICAL', 'Practical / Lab'), ('VIVA', 'Viva Voce'), ('OTHER', 'Other')], default='CIE', max_length=10)),
                ('max_marks', models.FloatField(default=100)),
                ('passing_marks', models.FloatField(default=40)),
                ('weightage_percent', models.FloatField(default=100, help_text='% contribution to final result')),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='students.college')),
            ],
            options={
                'unique_together': {('college', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_type',
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks_obtained', models.FloatField(default=0)),
                ('total_max_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('is_pass', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('PUBLISHED', 'Published'), ('WITHHELD', 'Withheld')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.exam')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('max_marks', models.FloatField(default=100)),
                ('passing_marks', models.FloatField(default=40)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='students.exam')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='students.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='students.subject')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.examtype')),
            ],
            options={
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('DETAINED', 'Detained — Low Attendance'), ('WITHHELD', 'Withheld — Fee Dues'), ('ISSUED', 'Hall Ticket Issued')], default='ELIGIBLE', max_length=10)),
                ('attendance_pct', models.FloatField(default=0)),
                ('has_fee_dues', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='students.exam')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='RevaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('revised_marks', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to='students.marks')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'marks')},
            },
        ),
    ]
