# Generated by Django 5.1.15 on 2026-04-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_exam_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_role', models.CharField(choices=[('COE', 'Controller of Examinations'), ('DEPUTY_COE', 'Deputy Controller'), ('SECTION_OFFICER', 'Section Officer'), ('VALUATION_OFFICER', 'Valuation Officer'), ('DATA_ENTRY', 'Data Entry Operator'), ('COORDINATOR', 'Exam Coordinator')], default='COORDINATOR', max_length=20)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_staff', to='students.college')),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this staff member is responsible for (leave blank for all)', related_name='exam_section_officers', to='students.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Staff',
                'verbose_name_plural': 'Exam Staff',
            },
        ),
        migrations.CreateModel(
            name='ExamStaffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SCHEDULE_CREATED', 'Schedule Created'), ('HALL_TICKET_ISSUED', 'Hall Ticket Issued'), ('MARKS_VERIFIED', 'Marks Verified'), ('RESULT_PUBLISHED', 'Result Published'), ('REVAL_PROCESSED', 'Revaluation Processed'), ('SCHEME_CHANGED', 'Evaluation Scheme Changed'), ('STAFF_ADDED', 'Exam Staff Added'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.exam')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.examstaff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "VTU B.E. Scheme 2021"', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cie_count', models.IntegerField(default=2, help_text='How many CIE tests are conducted')),
                ('cie_best_of', models.IntegerField(default=2, help_text='Best N CIE scores are counted (0 = all)')),
                ('cie_max_per_test', models.FloatField(default=30, help_text='Max marks per CIE test')),
                ('cie_total_max', models.FloatField(default=50, help_text='Total CIE contribution to final marks')),
                ('see_max', models.FloatField(default=100, help_text='SEE question paper max marks')),
                ('see_scaled_to', models.FloatField(default=50, help_text='SEE scaled contribution to final marks')),
                ('see_passing_min', models.FloatField(default=35, help_text='Minimum marks in SEE to pass')),
                ('has_practical', models.BooleanField(default=False)),
                ('practical_internal_max', models.FloatField(blank=True, default=25, null=True)),
                ('practical_external_max', models.FloatField(blank=True, default=25, null=True)),
                ('overall_passing_min', models.FloatField(default=40, help_text='Minimum % to pass overall')),
                ('grading_type', models.CharField(choices=[('ABSOLUTE', 'Absolute (fixed cutoffs)'), ('RELATIVE', 'Relative (based on class performance)'), ('CREDIT', 'Credit-based (CGPA)')], default='ABSOLUTE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schemes', to='students.college')),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank to apply to all departments in this college', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_schemes', to='students.department')),
            ],
            options={
                'unique_together': {('college', 'department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ValuationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_type', models.CharField(choices=[('FIRST', 'First Valuation'), ('SECOND', 'Second Valuation'), ('THIRD', 'Third / Arbitration')], default='FIRST', max_length=6)),
                ('external_name', models.CharField(blank=True, max_length=150)),
                ('external_institution', models.CharField(blank=True, max_length=200)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='students.examschedule')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_assignments', to='students.faculty')),
            ],
            options={
                'unique_together': {('exam_schedule', 'valuation_type')},
            },
        ),
    ]
