# Generated by Django 5.1.15 on 2026-04-01 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_exam_staff_schemes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='students.attendance')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason_type', models.CharField(choices=[('MEDICAL', 'Medical Leave'), ('SPORTS', 'Sports / Cultural Event'), ('OD', 'On Duty'), ('OTHER', 'Other Authorized Absence')], max_length=10)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='exemptions/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exemptions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, help_text='Leave blank to apply to all semesters', null=True)),
                ('min_overall_pct', models.FloatField(default=75.0, help_text='Minimum overall semester attendance % required')),
                ('min_subject_pct', models.FloatField(default=75.0, help_text='Minimum per-subject attendance % required')),
                ('require_both', models.BooleanField(default=True, help_text='Both overall AND subject-wise must be met')),
                ('grace_pct', models.FloatField(default=0.0, help_text='Condonation grace % (e.g. 5 means 70% is accepted)')),
                ('min_sessions_for_check', models.IntegerField(default=5, help_text='Minimum sessions conducted before eligibility check applies')),
                ('mandatory_subject_pct', models.FloatField(default=75.0, help_text='Stricter threshold for mandatory/core subjects')),
                ('allow_medical_exemption', models.BooleanField(default=True)),
                ('allow_sports_exemption', models.BooleanField(default=True)),
                ('allow_od_exemption', models.BooleanField(default=True)),
                ('max_exemption_days', models.IntegerField(default=15, help_text='Max days that can be exempted per semester')),
                ('alert_below_pct', models.FloatField(default=75.0, help_text='Send alert when attendance drops below this %')),
                ('critical_below_pct', models.FloatField(default=65.0, help_text='Send critical alert below this %')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='students.college')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank to apply to all departments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_rules', to='students.department')),
            ],
            options={
                'ordering': ['college', 'department', 'semester'],
                'unique_together': {('college', 'department', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='EligibilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('attendance_pct_at_request', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved — Eligible'), ('REJECTED', 'Rejected — Remains Ineligible')], default='PENDING', max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_overrides', to='students.exam')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overrides', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_overrides', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
