# Generated by Django 5.1.15 on 2026-04-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_attendance_rule_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this time after too many failed logins', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'code')},
        ),
    ]
