# Generated by Django 5.1.15 on 2026-04-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_tier1_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TUITION_REG', 'Tuition Fee - Regular Exam'), ('TUITION_LATERAL', 'Tuition Fee - Lateral Entry'), ('SEM_FEE', 'Semester Fee'), ('EXAM_REG', 'Exam Fee - Regular'), ('EXAM_BACK', 'Exam Fee - Backlog / Arrear'), ('EXAM_IMPROVE', 'Exam Fee - Improvement'), ('EXAM_REVAL', 'Revaluation Fee'), ('EXAM_PHOTOCOPY', 'Photocopy of Answer Script'), ('LAB_FEE', 'Lab Fee'), ('LIBRARY_FEE', 'Library Fee'), ('SPORTS_FEE', 'Sports & Cultural Fee'), ('TRANSPORT_FEE', 'Transport / Bus Fee'), ('HOSTEL_FEE', 'Hostel Fee'), ('CAUTION_DEPOSIT', 'Caution Deposit (Refundable)'), ('MISC', 'Miscellaneous / Other')], max_length=30)),
                ('amount', models.FloatField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='students.feestructure')),
            ],
            options={
                'unique_together': {('structure', 'category')},
            },
        ),
    ]
