# Generated by Django 5.1.15 on 2026-04-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_fee_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feebreakdown',
            name='category',
            field=models.CharField(choices=[('TUITION', 'Tuition Fee'), ('EXAM', 'Exam Fee'), ('LAB', 'Lab Fee'), ('LIBRARY', 'Library Fee'), ('SPORTS', 'Sports & Cultural Fee'), ('MISC', 'Miscellaneous'), ('SUPPLY_PER_SUBJECT', 'Supply Exam Fee (per subject)'), ('REVAL_PER_SUBJECT', 'Revaluation Fee (per subject)'), ('PHOTOCOPY', 'Photocopy of Answer Script')], max_length=30),
        ),
        migrations.CreateModel(
            name='SupplyExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Paid & Registered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_registrations', to='students.exam')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_registration', to='students.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_registrations', to='students.student')),
                ('subjects', models.ManyToManyField(related_name='supply_registrations', to='students.subject')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
