# Generated by Django 5.1.15 on 2026-04-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_student_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "VTU 2021 Scheme"', max_length=100)),
                ('code', models.CharField(help_text='Short code e.g. "VTU21", "R2019"', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('effective_from_year', models.IntegerField(help_text='Admission year from which this regulation applies (e.g. 2021)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='students.college')),
            ],
            options={
                'unique_together': {('college', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ElectivePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('slot_name', models.CharField(help_text='e.g. "PE-1", "Open Elective"', max_length=60)),
                ('elective_type', models.CharField(choices=[('PE', 'Program Elective'), ('OE', 'Open Elective')], default='PE', max_length=10)),
                ('quota_per_subject', models.PositiveIntegerField(default=60, help_text='Max students per elective subject')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Selection'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, help_text='Last date/time for students to submit their choice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_pools', to='students.department')),
                ('subjects', models.ManyToManyField(help_text='Subjects students can choose from in this slot', related_name='elective_pools', to='students.subject')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_pools', to='students.regulation')),
            ],
            options={
                'unique_together': {('regulation', 'department', 'semester', 'slot_name')},
            },
        ),
        migrations.CreateModel(
            name='ElectiveSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected — Quota Full'), ('CHANGED', 'Changed by Admin')], default='PENDING', max_length=10)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Admin note if changed/rejected', max_length=200)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='students.electivepool')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_selections', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_selections', to='students.subject')),
            ],
            options={
                'unique_together': {('student', 'pool')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('elective_type', models.CharField(choices=[('FIXED', 'Fixed / Compulsory'), ('PE', 'Program Elective'), ('OE', 'Open Elective')], default='FIXED', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='students.department')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Subjects that must be passed before taking this subject', related_name='required_for', to='students.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='students.subject')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='students.regulation')),
            ],
            options={
                'unique_together': {('regulation', 'department', 'subject', 'semester')},
            },
        ),
    ]
