# Generated by Django 5.1.15 on 2026-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_regulation_curriculum_electives'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivepool',
            name='min_students_per_subject',
            field=models.PositiveIntegerField(default=10, help_text='Min students needed to run this elective (below this, subject may be cancelled)'),
        ),
        migrations.AlterField(
            model_name='electivepool',
            name='quota_per_subject',
            field=models.PositiveIntegerField(default=60, help_text='Max students per elective subject (for section/faculty planning)'),
        ),
    ]
