# Generated by Django 5.1.15 on 2026-04-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_elective_pool_min_students'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section label e.g. A, B, C', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, help_text='Timetable slot this session was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='students.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('subject', 'date', 'section')},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('label', models.CharField(help_text='e.g. A, B, C', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('academic_year', models.CharField(blank=True, default='', help_text='e.g. 2023-24', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.department')),
            ],
            options={
                'ordering': ['department', 'semester', 'label'],
                'unique_together': {('department', 'semester', 'label')},
            },
        ),
        migrations.CreateModel(
            name='SectionSubjectFacultyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Default classroom for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classroom')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subject_maps', to='students.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_faculty_maps', to='students.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_faculty_maps', to='students.subject')),
            ],
            options={
                'ordering': ['section__label', 'subject__name'],
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
