# Generated by Django 5.1.15 on 2026-04-06 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_result_sgpa_grade_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_installments', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='students.fee')),
            ],
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(choices=[('MERIT', 'Merit Scholarship'), ('NEED', 'Need-based'), ('SPORTS', 'Sports Quota'), ('MANAGEMENT', 'Management Discretion'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.FloatField(help_text='Amount waived (Rs)')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waivers', to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='students.fee')),
            ],
        ),
        migrations.CreateModel(
            name='GraceMarksRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_grace_per_subject', models.FloatField(default=5.0, help_text='Max grace marks per subject')),
                ('max_grace_total', models.FloatField(default=10.0, help_text='Max total grace marks across all subjects')),
                ('apply_only_if_failing', models.BooleanField(default=True, help_text='Only apply grace to failing subjects')),
                ('requires_approval', models.BooleanField(default=True, help_text='Exam controller must approve each application')),
                ('is_active', models.BooleanField(default=True)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grace_rule', to='students.evaluationscheme')),
            ],
        ),
        migrations.CreateModel(
            name='GraceMarksApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_amount', models.FloatField(help_text='Grace marks to add')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied to Marks')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_approvals', to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_applications', to='students.marks')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_requests', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gracemarksrule')),
            ],
        ),
        migrations.CreateModel(
            name='LateFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_per_day', models.FloatField(default=50.0, help_text='Rs per day after due date')),
                ('max_penalty', models.FloatField(default=500.0, help_text='Maximum penalty cap (Rs)')),
                ('grace_days', models.IntegerField(default=7, help_text='Days after due date before penalty starts')),
                ('is_active', models.BooleanField(default=False)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rule', to='students.college')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MARKS_ENTERED', 'Marks Entered'), ('MARKS_UPDATED', 'Marks Updated'), ('MARKS_REVAL', 'Revaluation Applied'), ('ATT_MARKED', 'Attendance Marked'), ('ATT_CORRECTED', 'Attendance Corrected'), ('ATT_EXEMPTION', 'Exemption Granted'), ('ATT_OVERRIDE', 'Eligibility Override'), ('FEE_PAYMENT', 'Fee Payment'), ('FEE_WAIVER', 'Fee Waiver Applied'), ('FEE_PENALTY', 'Late Fee Penalty Added'), ('FEE_INSTALLMENT', 'Installment Updated'), ('ELECTIVE_SELECTED', 'Elective Selected'), ('ELECTIVE_CHANGED', 'Elective Changed by Admin'), ('TT_GENERATED', 'Timetable Generated'), ('TT_SUBSTITUTION', 'Substitution Assigned'), ('USER_CREATED', 'User Created'), ('USER_PROMOTED', 'Student Promoted'), ('RESULT_PUBLISHED', 'Result Published'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable summary of what changed')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON or plain text)')),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON or plain text)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='students.college')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='students.faculty')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='students.student')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', 'timestamp'], name='students_au_action__5513db_idx'), models.Index(fields=['student', 'timestamp'], name='students_au_student_6eccc5_idx'), models.Index(fields=['college', 'timestamp'], name='students_au_college_ff6748_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='1, 2, 3…')),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment', to='students.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.feeinstallmentplan')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('plan', 'number')},
            },
        ),
    ]
