# Generated by Django 5.1.15 on 2026-04-06 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_audit_log_fee_installment_grace_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DETAINED', 'Detained'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='CollegeFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_electives', models.BooleanField(default=True)),
                ('enable_online_payment', models.BooleanField(default=True)),
                ('enable_quiz_module', models.BooleanField(default=True)),
                ('enable_assignment_module', models.BooleanField(default=True)),
                ('enable_lesson_plans', models.BooleanField(default=True)),
                ('enable_helpdesk', models.BooleanField(default=True)),
                ('enable_supply_exam', models.BooleanField(default=True)),
                ('enable_revaluation', models.BooleanField(default=True)),
                ('enable_grace_marks', models.BooleanField(default=False)),
                ('enable_fee_installments', models.BooleanField(default=False)),
                ('enable_late_fee_penalty', models.BooleanField(default=False)),
                ('enable_disciplinary_check', models.BooleanField(default=False)),
                ('require_hod_for_attendance_correction', models.BooleanField(default=False)),
                ('require_principal_for_result_publish', models.BooleanField(default=False)),
                ('auto_promote_students', models.BooleanField(default=False, help_text='Auto-promote at semester end if passing')),
                ('elective_allocation_mode', models.CharField(choices=[('MANUAL', 'Manual (admin confirms)'), ('AUTO_CGPA', 'Auto by CGPA'), ('FCFS', 'First Come First Served')], default='MANUAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='students.college')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('APPEALED', 'Under Appeal')], default='ACTIVE', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disciplinary', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disciplinary', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='MarksModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_type', models.CharField(choices=[('ADD', 'Add flat marks to all'), ('SCALE', 'Scale by multiplier'), ('CAP', 'Cap at maximum')], max_length=10)),
                ('value', models.FloatField(help_text='Marks to add, multiplier, or cap value')),
                ('reason', models.TextField()),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_moderations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_moderations', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='students.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='students.subject')),
            ],
        ),
        migrations.CreateModel(
            name='RegulationMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('backlog_subjects', models.ManyToManyField(blank=True, help_text='Subjects carried over as backlogs from old regulation', related_name='backlog_migrations', to='students.subject')),
                ('from_regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_from', to='students.regulation')),
                ('migrated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_migrations', to='students.student')),
                ('to_regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_to', to='students.regulation')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PROMOTED', 'Promoted to next semester'), ('DETAINED', 'Detained — failed to meet criteria'), ('REINSTATED', 'Reinstated after detention'), ('SUSPENDED', 'Suspended — disciplinary action'), ('UNSUSPENDED', 'Suspension lifted'), ('DROPPED', 'Dropped out'), ('READMITTED', 'Re-admitted'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred to another institution')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('from_semester', models.IntegerField(blank=True, null=True)),
                ('to_semester', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_lateral', models.BooleanField(default=False, help_text='True for lateral entry students')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='students.regulation')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_assignment', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSchemeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_overrides', to='students.evaluationscheme')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_override', to='students.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position in queue (1 = next to be allocated)')),
                ('cgpa', models.FloatField(default=0.0, help_text='CGPA at time of waitlisting — used for priority sorting')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('promoted', models.BooleanField(default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='students.electivepool')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_waitlist', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='students.subject')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('student', 'pool', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamEligibilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_attendance', models.BooleanField(default=True)),
                ('min_attendance_pct', models.FloatField(default=75.0)),
                ('check_fee_clearance', models.BooleanField(default=True)),
                ('allow_partial_fee', models.BooleanField(default=False, help_text='Allow if at least partial payment made')),
                ('check_internal_marks', models.BooleanField(default=False)),
                ('min_internal_marks_pct', models.FloatField(default=0.0, help_text='Min % of internal marks to be eligible')),
                ('check_disciplinary', models.BooleanField(default=False, help_text='Block if student has active disciplinary action')),
                ('require_all_gates', models.BooleanField(default=True, help_text='True = AND logic; False = OR logic')),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_configs', to='students.college')),
                ('exam', models.ForeignKey(blank=True, help_text='Leave blank for college-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_configs', to='students.exam')),
            ],
            options={
                'unique_together': {('college', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ResultFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('unfreeze_reason', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_freezes', to='students.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_records', to='students.exam')),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_results', to=settings.AUTH_USER_MODEL)),
                ('unfrozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfrozen_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('college', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ResultVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('sgpa', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('snapshot_reason', models.CharField(help_text='e.g. "Before revaluation", "Before moderation"', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='students.result')),
            ],
            options={
                'ordering': ['-version_no'],
                'unique_together': {('result', 'version_no')},
            },
        ),
    ]
