# Generated by Django 5.1.15 on 2026-04-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_regulation_versioning_lifecycle_eligibility_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('regular', 'Regular'), ('lateral_entry', 'Lateral Entry'), ('nri', 'NRI'), ('management', 'Management Quota'), ('transfer', 'Transfer')], default='regular', max_length=15)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('confirmed', 'Confirmed'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=10)),
                ('category', models.CharField(blank=True, default='', help_text='e.g. GEN, OBC, SC, ST, EWS', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2024-25', max_length=10)),
                ('round_number', models.IntegerField(default=1, help_text='1 = first round, 2 = second round, etc.')),
                ('round_name', models.CharField(blank=True, default='', help_text="e.g. 'Regular', 'Lateral Entry', 'NRI', 'Management Quota'", max_length=60)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['academic_year', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='BacklogRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_semester', models.IntegerField(help_text='Semester the student originally failed this subject')),
                ('semester_registered', models.IntegerField(help_text='Semester in which the student is re-attending this subject')),
                ('academic_year', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attending', 'Attending'), ('cleared', 'Cleared / Passed'), ('failed', 'Failed Again'), ('withdrawn', 'Withdrawn')], default='registered', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_label', models.CharField(default='', help_text='Auto-assigned label e.g. EG-A, EG-B', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyFeedbackCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('questions', models.TextField(default='Clarity of teaching\nSubject knowledge\nPunctuality and preparation\nStudent engagement\nDoubt clarification')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyFeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.JSONField(default=dict)),
                ('comments', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LateralEntryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_semester', models.IntegerField(default=3, help_text='Semester the student joined (usually 3 for LE)')),
                ('previous_qualification', models.CharField(blank=True, default='', help_text='e.g. Diploma in Computer Science', max_length=200)),
                ('previous_institution', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_semester', models.IntegerField(help_text='Semester being completed')),
                ('min_credits_required', models.IntegerField(default=0, help_text='Minimum credits student must have passed to be promoted')),
                ('min_attendance_pct', models.FloatField(default=75.0, help_text='Minimum overall attendance % required for promotion')),
                ('allow_backlogs', models.BooleanField(default=True, help_text='If True, students with backlogs can still be promoted to next semester')),
                ('max_backlogs_allowed', models.IntegerField(default=2, help_text='Max number of backlog subjects allowed for promotion (if allow_backlogs=True)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('faculty_clash', 'Faculty Clash'), ('room_clash', 'Room Clash'), ('student_group_clash', 'Student Group Clash'), ('faculty_availability', 'Faculty Availability'), ('time_distribution', 'Time Distribution'), ('room_type_match', 'Room Type Match'), ('slot_duration_match', 'Slot Duration Match')], max_length=30)),
                ('priority', models.CharField(choices=[('hard', 'Hard — Must Satisfy'), ('soft', 'Soft — Preference')], default='hard', max_length=10)),
                ('weight', models.IntegerField(default=10, help_text='1 (low) to 100 (high). Used for soft constraint optimization.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResultBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveIntegerField()),
                ('source_file', models.FileField(upload_to='semester_results/uploads/')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='semester_results/generated/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved')], default='UPLOADED', max_length=12)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('subject_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResultStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number_snapshot', models.CharField(max_length=50)),
                ('username_snapshot', models.CharField(max_length=150)),
                ('full_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('total_marks_obtained', models.FloatField(default=0)),
                ('total_max_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('sgpa', models.FloatField(default=0)),
                ('cgpa', models.FloatField(default=0)),
                ('semester_credits', models.PositiveIntegerField(default=0)),
                ('overall_credits', models.PositiveIntegerField(default=0)),
                ('result_status', models.CharField(default='PASS', max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='semester_results/students/')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('APPROVED', 'Approved')], default='GENERATED', max_length=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['student__roll_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResultSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code_snapshot', models.CharField(max_length=50)),
                ('subject_name_snapshot', models.CharField(max_length=255)),
                ('marks_obtained', models.FloatField(default=0)),
                ('max_marks', models.FloatField(default=100)),
                ('grade', models.CharField(blank=True, default='', max_length=5)),
                ('grade_point', models.FloatField(default=0.0)),
                ('status', models.CharField(default='PASS', max_length=10)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'subject_code_snapshot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroupConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('section', 'Department Section'), ('elective', 'Elective Group')], max_length=10)),
                ('group_id', models.IntegerField(help_text='PK of Section or ElectiveGroup')),
                ('day_of_week', models.CharField(choices=[], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentSemesterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(blank=True, default='', help_text='e.g. 2023-24', max_length=10)),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('detained', 'Detained — Must Repeat Semester'), ('backlog', 'Promoted with Backlog'), ('dropped', 'Dropped Out'), ('graduated', 'Graduated')], max_length=10)),
                ('credits_earned', models.IntegerField(default=0)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['student', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('regular', 'Regular Timetable'), ('exam', 'Exam Timetable'), ('backup', 'Backup Timetable'), ('draft', 'Draft / Proposed')], default='regular', max_length=10)),
                ('version_name', models.CharField(help_text="e.g. 'Regular 2024-25 Odd', 'Exam Dec 2024', 'Backup Rainy Day'", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one version per type can be active. Activating this deactivates others of same type.')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF or image attachment', null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Limit to a specific department (leave blank for college-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_announcements', to='students.department'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('all', 'Everyone (Faculty + Students)'), ('faculty', 'Faculty Only'), ('students', 'Students Only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('ONLINE', 'Online — students upload file'), ('OFFLINE', 'Offline — physical submission')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='topic_covered',
            field=models.CharField(blank=True, default='', help_text='Topic taught in this session', max_length=300),
        ),
        migrations.AddField(
            model_name='classroom',
            name='features',
            field=models.CharField(blank=True, default='', help_text='Comma-separated features e.g. projector,computers,ac,smartboard', max_length=200),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Lab'), ('seminar', 'Seminar Hall'), ('tutorial', 'Tutorial Room'), ('other', 'Other')], default='lecture', help_text='Type of room — used by generator to match subject slot type', max_length=10),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='course_registration_open',
            field=models.BooleanField(default=False, help_text='When True, students can see and submit course registration for the next semester.'),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='course_registration_semester',
            field=models.IntegerField(blank=True, help_text='Which semester the open registration window is for (e.g. 3 means Sem 3 registration is open).', null=True),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='max_casual_leaves',
            field=models.IntegerField(default=12, help_text='Max Casual Leave days per faculty per year'),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='max_earned_leaves',
            field=models.IntegerField(default=15, help_text='Max Earned Leave days per faculty per year'),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='max_medical_leaves',
            field=models.IntegerField(default=10, help_text='Max Medical Leave days per faculty per year'),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='max_od_leaves',
            field=models.IntegerField(default=20, help_text='Max On Duty days per faculty per year'),
        ),
        migrations.AddField(
            model_name='collegefeatureconfig',
            name='max_substitutions',
            field=models.IntegerField(default=10, help_text='Max substitution requests per faculty per semester'),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='availability_type',
            field=models.CharField(choices=[('available', 'Available'), ('preferred', 'Preferred'), ('blocked', 'Blocked / Unavailable')], default='available', help_text='available = can teach, preferred = prefers this slot, blocked = unavailable', max_length=10),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='notes',
            field=models.CharField(blank=True, default='', help_text="Optional note e.g. 'Can take labs only', 'Unavailable during exams'", max_length=200),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='priority_score',
            field=models.IntegerField(default=5, help_text='1 (low) to 10 (high). Generator prefers higher scores when multiple slots are valid.'),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Leave blank for permanent. Set for temporary slots (e.g. leave period).', null=True),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Leave blank for permanent.', null=True),
        ),
        migrations.AddField(
            model_name='hallticket',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hallticket',
            name='row_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hallticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hod',
            name='can_take_classes',
            field=models.BooleanField(default=False, help_text='Enable if this HOD also teaches subjects like a faculty member'),
        ),
        migrations.AddField(
            model_name='hod',
            name='designation',
            field=models.CharField(default='Head of Department', help_text='e.g. Professor & Head, Associate Professor & Head', max_length=100),
        ),
        migrations.AddField(
            model_name='hod',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='hod',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='Research/teaching specialization areas', max_length=200),
        ),
        migrations.AddField(
            model_name='hodapproval',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approvals', to='students.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='access_password',
            field=models.CharField(blank=True, default='', help_text='Optional password students must enter before starting the quiz.', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions_per_student',
            field=models.PositiveIntegerField(blank=True, help_text='How many questions each student gets (random from pool). Leave blank = all questions.', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='template_file',
            field=models.FileField(blank=True, help_text='Upload a CSV/Excel with questions to bulk-import into the pool.', null=True, upload_to='quiz_templates/'),
        ),
        migrations.AddField(
            model_name='section',
            name='criteria',
            field=models.CharField(choices=[('auto', 'Auto — by roll number / count'), ('manual', 'Manual — admin assigned'), ('merit_based', 'Merit Based'), ('gender', 'Gender Based'), ('specialization', 'Specialization Based')], default='auto', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('lateral_entry', 'Lateral Entry'), ('transfer', 'Transfer')], default='regular', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_semester',
            field=models.IntegerField(default=1, help_text='Semester student joined (1 for regular, 3 for lateral entry)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', help_text='Alternate/secondary mobile number', max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_email',
            field=models.EmailField(blank=True, help_text='Institutional email assigned by college (read-only for student)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Student personal email (read-only for student)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='frequency_per_week',
            field=models.IntegerField(default=3, help_text='How many times per week this subject meets'),
        ),
        migrations.AddField(
            model_name='subject',
            name='scheduling_constraint',
            field=models.CharField(blank=True, choices=[('', 'None'), ('no_consecutive', 'No Consecutive Slots'), ('prefer_morning', 'Prefer Morning'), ('prefer_afternoon', 'Prefer Afternoon'), ('continuous_block', 'Continuous Block (e.g. 3-hr lab)'), ('alternate_days', 'Alternate Days Only')], default='', help_text='Optional scheduling constraint for the generator', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='slot_duration_mins',
            field=models.IntegerField(default=60, help_text='Duration of each slot in minutes (e.g. 60 for lecture, 120 for lab)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slot_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab / Practical'), ('tutorial', 'Tutorial'), ('seminar', 'Seminar')], default='lecture', help_text='Primary slot type for scheduling', max_length=10),
        ),
        migrations.AddField(
            model_name='substitution',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Optional reason/note shown to the substitute faculty', max_length=500),
        ),
        migrations.AddField(
            model_name='substitution',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='substitution',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substitution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='substitution',
            name='topic_covered',
            field=models.CharField(blank=True, default='', help_text='Topic covered — required before marking attendance', max_length=300),
        ),
        migrations.AddField(
            model_name='timetable',
            name='generation_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manual / CSV Upload'), ('strict', 'Auto — Strict'), ('balanced', 'Auto — Balanced'), ('faculty_priority', 'Auto — Faculty Priority')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked slots are skipped by auto-generator. Admin must unlock to allow changes.'),
        ),
        migrations.AddField(
            model_name='timetablebreak',
            name='applies_to',
            field=models.CharField(choices=[('college', 'Entire College'), ('department', 'Department Only'), ('section', 'Specific Section')], default='college', help_text='Scope of this break', max_length=10),
        ),
        migrations.AddField(
            model_name='timetablebreak',
            name='break_type',
            field=models.CharField(choices=[('regular', 'Regular Break'), ('exam', 'Exam / Test'), ('event', 'College Event / Fest'), ('holiday', 'Holiday'), ('other', 'Other')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='timetablebreak',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Set only when applies_to = department or section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_breaks', to='students.department'),
        ),
        migrations.AddField(
            model_name='timetablebreak',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section label if applies_to = section', max_length=10),
        ),
        migrations.AddField(
            model_name='timetablebreak',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Start date for temporary breaks (events, exams). Leave blank for recurring.', null=True),
        ),
        migrations.AddField(
            model_name='timetablebreak',
            name='valid_to',
            field=models.DateField(blank=True, help_text='End date for temporary breaks.', null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='hodapproval',
            name='approval_type',
            field=models.CharField(choices=[('LEAVE', 'Leave Request'), ('EVENT', 'Event Approval'), ('COURSE', 'Course Approval'), ('CE_MARKS', 'CE Marks Submission')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['faculty', 'date'], name='attsess_faculty_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['subject', 'date'], name='attsess_subject_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['faculty', 'status'], name='leave_faculty_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['faculty', 'from_date'], name='leave_faculty_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notif_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['original_faculty', 'date', 'status'], name='sub_orig_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['substitute_faculty', 'date', 'status'], name='sub_sub_date_status_idx'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_cycles', to='students.college'),
        ),
        migrations.AddField(
            model_name='admission',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='students.admissioncycle'),
        ),
        migrations.AddField(
            model_name='backlogregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_registrations', to='students.student'),
        ),
        migrations.AddField(
            model_name='backlogregistration',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_registrations', to='students.subject'),
        ),
        migrations.AddField(
            model_name='backlogregistration',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, help_text='The specific timetable slot the student is attending for this backlog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlog_students', to='students.timetable'),
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='students.electivepool'),
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students in this elective group (populated from confirmed ElectiveSelections)', related_name='elective_groups', to='students.student'),
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='students.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='elective_group',
            field=models.ForeignKey(blank=True, help_text='Set for elective group slots to enable student-level conflict detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='students.electivegroup'),
        ),
        migrations.AddField(
            model_name='facultyfeedbackcycle',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_feedback_cycles', to='students.college'),
        ),
        migrations.AddField(
            model_name='facultyfeedbackcycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedback_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyfeedbackcycle',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_feedback_cycles', to='students.department'),
        ),
        migrations.AddField(
            model_name='facultyfeedbackcycle',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_cycles', to='students.faculty'),
        ),
        migrations.AddField(
            model_name='facultyfeedbackcycle',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_cycles', to='students.subject'),
        ),
        migrations.AddField(
            model_name='facultyfeedbackresponse',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='students.facultyfeedbackcycle'),
        ),
        migrations.AddField(
            model_name='facultyfeedbackresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_feedback_responses', to='students.student'),
        ),
        migrations.AddField(
            model_name='lateralentryprofile',
            name='bridge_courses',
            field=models.ManyToManyField(blank=True, help_text='Additional subjects LE student must complete', related_name='bridge_course_students', to='students.subject'),
        ),
        migrations.AddField(
            model_name='lateralentryprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_entry_profile', to='students.student'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='students.college'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for college-wide rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_rules', to='students.department'),
        ),
        migrations.AddField(
            model_name='schedulingconstraint',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_constraints', to='students.college'),
        ),
        migrations.AddField(
            model_name='semesterresultbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_semester_result_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterresultbatch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_batches', to='students.college'),
        ),
        migrations.AddField(
            model_name='semesterresultbatch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_batches', to='students.department'),
        ),
        migrations.AddField(
            model_name='semesterresultbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_result_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterresultstudent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_semester_result_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterresultstudent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='students.semesterresultbatch'),
        ),
        migrations.AddField(
            model_name='semesterresultstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_transcripts', to='students.student'),
        ),
        migrations.AddField(
            model_name='semesterresultsubject',
            name='student_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.semesterresultstudent'),
        ),
        migrations.AddField(
            model_name='semesterresultsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_subjects', to='students.subject'),
        ),
        migrations.AddField(
            model_name='studentgroupconflict',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_conflicts', to='students.college'),
        ),
        migrations.AddField(
            model_name='studentgroupconflict',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_group_conflicts', to='students.timetable'),
        ),
        migrations.AddField(
            model_name='studentsemesterhistory',
            name='backlogs',
            field=models.ManyToManyField(blank=True, help_text='Subjects the student failed / has backlog in', related_name='backlog_students', to='students.subject'),
        ),
        migrations.AddField(
            model_name='studentsemesterhistory',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsemesterhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_versions', to='students.college'),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='version',
            field=models.ForeignKey(blank=True, help_text='Link to timetable version (regular/exam/backup/draft)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='students.timetableversion'),
        ),
        migrations.AlterUniqueTogether(
            name='admissioncycle',
            unique_together={('college', 'academic_year', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='backlogregistration',
            unique_together={('student', 'subject', 'semester_registered', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='electivegroup',
            unique_together={('pool', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='facultyfeedbackresponse',
            unique_together={('cycle', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='promotionrule',
            unique_together={('college', 'department', 'from_semester')},
        ),
        migrations.AlterUniqueTogether(
            name='schedulingconstraint',
            unique_together={('college', 'constraint_type')},
        ),
        migrations.AlterUniqueTogether(
            name='semesterresultbatch',
            unique_together={('college', 'department', 'academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='semesterresultstudent',
            unique_together={('batch', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='semesterresultsubject',
            unique_together={('student_result', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgroupconflict',
            unique_together={('group_type', 'group_id', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsemesterhistory',
            unique_together={('student', 'semester', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableversion',
            unique_together={('college', 'version_name')},
        ),
    ]
