from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('helpdesk/', views.helpdesk_view, name='helpdesk'),
    path('sys/platform-access/', views.super_admin_login_view, name='super_admin_login'),
    path('superadmin1/', views.super_admin_dashboard, name='super_admin_dashboard'),
    path('superadmin1/colleges/add/', views.super_admin_college_add, name='super_admin_college_add'),
    path('superadmin1/colleges/<int:pk>/edit/', views.super_admin_college_edit, name='super_admin_college_edit'),
    path('superadmin1/colleges/<int:pk>/toggle/', views.super_admin_college_toggle, name='super_admin_college_toggle'),
    path('superadmin1/colleges/<int:pk>/', views.super_admin_college_detail, name='super_admin_college_detail'),
    path('superadmin1/college-admins/add/', views.super_admin_college_admin_add, name='super_admin_college_admin_add'),
    path('superadmin1/college-admins/<int:pk>/delete/', views.super_admin_college_admin_delete, name='super_admin_college_admin_delete'),
    path('superadmin1/announcements/', views.super_admin_platform_announcement, name='super_admin_platform_announcement'),
    path('superadmin1/announcements/<int:pk>/delete/', views.super_admin_platform_announcement_delete, name='super_admin_platform_announcement_delete'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='auth/password_reset_form.html',
            email_template_name='auth/password_reset_email.txt',
            subject_template_name='auth/password_reset_subject.txt',
        ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'),
        name='password_reset_complete',
    ),

    path('dashboard/', views.dashboard_redirect, name='dashboard'),

    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/admin/departments/', views.admin_departments, name='admin_departments'),
    path('dashboard/admin/departments/add/', views.admin_department_add, name='admin_department_add'),
    path('dashboard/admin/departments/<int:pk>/edit/', views.admin_department_edit, name='admin_department_edit'),
    path('dashboard/admin/departments/<int:pk>/delete/', views.admin_department_delete, name='admin_department_delete'),
    path('dashboard/admin/bulk-import/', views.admin_bulk_import, name='admin_bulk_import'),
    path('dashboard/admin/bulk-import/sample/', views.admin_sample_csv, name='admin_sample_csv'),
    path('dashboard/admin/students/', views.admin_students, name='admin_students'),
    path('dashboard/admin/students/add/', views.admin_student_add, name='admin_student_add'),
    path('dashboard/admin/students/bulk-promote/', views.admin_students_bulk_promote, name='admin_students_bulk_promote'),
    path('dashboard/admin/students/export/csv/', views.admin_students_export_csv, name='admin_students_export_csv'),
    path('dashboard/admin/registration-requests/', views.admin_registration_requests, name='admin_registration_requests'),
    path('dashboard/admin/registration-requests/<int:pk>/update/', views.admin_registration_request_update, name='admin_registration_request_update'),
    path('dashboard/admin/student-invites/', views.admin_registration_invites, name='admin_registration_invites'),
    path('dashboard/admin/students/<int:pk>/edit/', views.admin_student_edit, name='admin_student_edit'),
    path('dashboard/admin/students/<int:pk>/delete/', views.admin_student_delete, name='admin_student_delete'),
    path('dashboard/admin/faculty/', views.admin_faculty_list, name='admin_faculty_list'),
    path('dashboard/admin/faculty/add/', views.admin_faculty_add, name='admin_faculty_add'),
    path('dashboard/admin/faculty/<int:pk>/edit/', views.admin_faculty_edit, name='admin_faculty_edit'),
    path('dashboard/admin/faculty/<int:pk>/delete/', views.admin_faculty_delete, name='admin_faculty_delete'),
    path('dashboard/admin/hods/', views.admin_hods, name='admin_hods'),
    path('dashboard/admin/hods/add/', views.admin_hod_add, name='admin_hod_add'),
    path('dashboard/admin/hods/<int:pk>/delete/', views.admin_hod_delete, name='admin_hod_delete'),
    path('dashboard/admin/subjects/', views.admin_subjects, name='admin_subjects'),
    path('dashboard/admin/subjects/add/', views.admin_subject_add, name='admin_subject_add'),
    path('dashboard/admin/subjects/<int:pk>/delete/', views.admin_subject_delete, name='admin_subject_delete'),
    path('dashboard/admin/academic-planner/', views.admin_academic_planner, name='admin_academic_planner'),
    path('dashboard/admin/fees/', views.admin_fees, name='admin_fees'),
    path('dashboard/admin/fees/add/', views.admin_fee_add, name='admin_fee_add'),
    path('dashboard/admin/fees/<int:pk>/edit/', views.admin_fee_edit, name='admin_fee_edit'),
    path('dashboard/admin/announcements/', views.admin_announcements, name='admin_announcements'),
    path('dashboard/admin/announcements/add/', views.admin_announcement_add, name='admin_announcement_add'),
    path('dashboard/admin/announcements/<int:pk>/delete/', views.admin_announcement_delete, name='admin_announcement_delete'),
    path('dashboard/admin/helpdesk/', views.admin_helpdesk, name='admin_helpdesk'),
    path('dashboard/admin/helpdesk/<int:pk>/update/', views.admin_helpdesk_update, name='admin_helpdesk_update'),
    path('dashboard/helpdesk/ticket/<int:pk>/', views.ticket_detail_view, name='ticket_detail'),
    path('dashboard/admin/exams/', views.admin_exams, name='admin_exams'),
    path('dashboard/admin/exams/add/', views.admin_exam_add, name='admin_exam_add'),
    path('dashboard/admin/exams/<int:pk>/delete/', views.admin_exam_delete, name='admin_exam_delete'),
    path('dashboard/admin/attendance/export/', views.admin_attendance_export_csv, name='admin_attendance_export_csv'),
    path('dashboard/admin/save-colors/', views.admin_save_colors, name='admin_save_colors'),

    path('dashboard/hod/', views.hod_dashboard, name='hod_dashboard'),
    path('dashboard/hod/approve/<int:pk>/', views.hod_approve, name='hod_approve'),
    path('dashboard/hod/substitutions/', views.hod_substitutions, name='hod_substitutions'),
    path('dashboard/principal/', views.principal_dashboard, name='principal_dashboard'),
    path('dashboard/faculty/', views.faculty_dashboard, name='faculty_dashboard'),
    path('dashboard/faculty/requests/add/', views.faculty_request_add, name='faculty_request_add'),
    path('dashboard/faculty/attendance/<int:subject_id>/', views.faculty_mark_attendance, name='faculty_mark_attendance'),
    path('dashboard/faculty/marks/<int:subject_id>/<int:exam_id>/', views.faculty_enter_marks, name='faculty_enter_marks'),
    path('dashboard/faculty/assignments/create/', views.faculty_assignment_create, name='faculty_assignment_create'),
    path('dashboard/faculty/assignments/<int:pk>/publish/', views.faculty_assignment_publish, name='faculty_assignment_publish'),
    path('dashboard/faculty/submissions/<int:pk>/review/', views.faculty_review_submission, name='faculty_review_submission'),
    path('dashboard/faculty/quiz/', views.faculty_quiz_list, name='faculty_quiz_list'),
    path('dashboard/faculty/quiz/create/', views.faculty_quiz_create, name='faculty_quiz_create'),
    path('dashboard/faculty/quiz/<int:pk>/edit/', views.faculty_quiz_edit, name='faculty_quiz_edit'),
    path('dashboard/faculty/quiz/<int:pk>/results/', views.faculty_quiz_results, name='faculty_quiz_results'),
    path('dashboard/faculty/internal-marks/<int:subject_id>/', views.faculty_internal_marks, name='faculty_internal_marks'),
    path('dashboard/faculty/attendance/<int:subject_id>/defaulters/', views.faculty_attendance_defaulters, name='faculty_attendance_defaulters'),
    path('dashboard/faculty/lesson-plans/<int:subject_id>/', views.faculty_lesson_plans, name='faculty_lesson_plans'),
    path('dashboard/faculty/leave/', views.faculty_leave_apply, name='faculty_leave_apply'),
    path('dashboard/lab/', views.lab_staff_dashboard, name='lab_staff_dashboard'),
    path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
    path('dashboard/student/profile/edit/', views.student_profile_edit, name='student_profile_edit'),
    path('dashboard/student/assignments/<int:pk>/submit/', views.student_submit_assignment, name='student_submit_assignment'),
    path('dashboard/student/fees/pay/', views.student_fee_payment, name='student_fee_payment'),
    path('dashboard/student/payments/<int:pk>/receipt/', views.student_payment_receipt, name='student_payment_receipt'),
    path('dashboard/student/payments/<int:pk>/receipt/pdf/', views.student_payment_receipt_pdf, name='student_payment_receipt_pdf'),
    path('dashboard/student/results/report/pdf/', views.student_result_report_pdf, name='student_result_report_pdf'),
    path('dashboard/student/quiz/<int:quiz_id>/attempt/', views.student_quiz_attempt, name='student_quiz_attempt'),
    path('dashboard/admin/reports/<str:report_type>/pdf/', views.admin_report_pdf, name='admin_report_pdf'),
]
